### ISSUE TITLE
random scroll in a scroll area

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#10]
I have a scroll area with many widgets in a vertical box layout. One of the widgets contains a TileLayout and when i drag and drop, sometime the scroll area scrolls to seemingly random position.

I have tracked the problem to here: https://www.qtcentre.org/threads/18363-QScrollArea-How-to-avoid-automatic-scroll-actions

And i have submitted a PR with a very simple change that solves the issue. #11

**Comment by arnaudframmery** [comment]
Thank you very much ! I will do the package update by the end of the week, maybe with the highlight tiles when resizing feature

**Comment by andreasharbo** [comment]
That sounds great, that would also be a nice addition 💯

**Comment by arnaudframmery** [comment]
It seems to work well but if you want to test it before merging (in 2-3 days maybe) here is the PR: #12
