### ISSUE TITLE
feature/Drag and drop a widget/tile from one TileLayout to another

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#16]

**Comment by arnaudframmery** [comment]
It seems to be not so hard to implement, we can think of a method to link two TileLayout and therefore authorize the drag and drop between the two of them :

`tile_layout_1.link(tile_layout_2)`

I will try to implement this feature during the next month

**Comment by arnaudframmery** [comment]
In fact it's already here 🥳
Feel free to test it and give a feedback
