### ISSUE TITLE
parentless tiles floating over widgets after resize or move

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#3]
If tile has rowSpan og columnSpan larger than 1, moving or resizing them sometimes results in floating parentless 'idle' tiles.

This is the case, at least with PyQt 5.12.2. Not the case on 5.15.x.
Have not tested multiple versions.

**Comment by arnaudframmery** [comment]
Thank you again for the PR, now that it's resolved I close this issue :)
