### ISSUE TITLE
dragEnterEvent doesn't catch JSONDecodeError

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#4]
When dragging something into the layout that is not a Tile, the ´__isDropPossible´ method throws an error. This should be caught and possibly ignored to allow other dragEnterEvents to happen on the layout.

Use-case: I want to drop a new tile one the layout, and i am using the mimeData for details about the creation of the widget, and then using the dropEvent handler in my parent widget to create and insert it into the layout. This error should then be ignored.

```
Traceback (most recent call last):
  File "../main.py", line 110, in <module>
    exit_code = appctxt.run()  # run program
  File "../main.py", line 100, in run
    return self.app.exec_()
  File "../API\Widgets\BaseWidgets\Tree\Tree.py", line 172, in startDrag
    drag.exec_(QtCore.Qt.CopyAction)
  File "..\site-packages\QTileLayout\tile.py", line 150, in dragEnterEvent
    if self.tileLayout.dragAndDrop and self.__isDropPossible(event):
  File "..\site-packages\QTileLayout\tile.py", line 222, in __isDropPossible
    dropData = json.loads(event.mimeData().text())
  File "..\py36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "../py36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "..\py36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by arnaudframmery** [comment]
Thank you for your report !

Yes I see the issue, there is also the fact that you can drop a tile in a text editor for exemple and the drop will be accepted, so the tile is lost ^^'

There will also be an issue if we try to move a tile from a tile layout to another one in fact.

I think that the best solution is to create a custom mime data to avoid all these issues. I will try to do that this week and then create a PR so you will be able to test it and give me some feed backs before merging (if you want of course)

**Comment by andreasharbo** [comment]
I will gladly test any solution you come up with :)

The part about dragging a tile from one TileLayout to another is actually a feature request of mine :)

**Comment by arnaudframmery** [comment]
I think that the PR is ready, you can check it out and give some feedbacks if you have any (I would probably merge it on monday evening).

After some tests with PyQt 5.15 and 5.12 it seems to work very well !

**Comment by andreasharbo** [comment]
More urgent stuff has come in the way of my further GUI development with your Tile layout. 

I have allocated sometime next week to take a look at it, probably not before wednesday.

**Comment by arnaudframmery** [comment]
No problem take your time, there is no urgency :)

**Comment by andreasharbo** [comment]
The new requirements for PyQt 5.15 in your version 1.2 i messing with my venv 😄 

I suggest you merge this, and i will promptly submit any issues i find, if any.

Also, take a look at my comment on the earlier PR, i don't seem to get the changes when i update the package?

**Comment by arnaudframmery** [comment]
Ok, I will do that and publish the version 0.1.3 on PyPi today.

If all goes well the version and drag and drop issues should be corrected 🤞

**Comment by arnaudframmery** [comment]
So after merging the PR and update the PyPi package I checked this new version on another project and all the modifications are present 🙌

As you said, feel free to open another issue if there is a persistent bug

**Comment by andreasharbo** [comment]
I have updated and the changes are now there. It works great, i can drop my widgets just as expected :)

Thank you for the quick work!
