### ISSUE TITLE
it is undetermined which widget has focus after a mousePressEvent

### ISSUE THREAD

**Issue by andreasharbo** [arnaudframmery/qt-tile-layout#6]
When pressing, dragging or resizing a widget the QApplication.focusWidget is not the widget that was just clicked, moved or resized, but some other widget in the layout (possibly, seems to be random).

It seems to be this series of lines in `tile.py`, the `mousePressEvent` method that are causing the problems.

```
        elif self.filled and self.tileLayout.dragAndDrop:
            drag = self.__prepareDropData(event)
            self.__dragAndDropProcess(drag)
            self.tileLayout.changeTilesColor('idle')
```

Here the widget of the tile are hidden and shown, which i think is the cause of the shift of focusWidget.

I have two different suggestions to a solution.

1. (quick)

In the end of the mousePressEvent set the focus with ´widget.setFocus()´ back to the widget of the Tile. Be aware that if a widget spans multiple Tiles, only the top left corner Tile seems to have a reference to the widget, so if i click the widget over the most 'southern' Tile it is spanning the widget is None for that tile. 

2. (better, maybe slower)

Dont do the drag before an actual drag event happens. I'm not sure if this fixes the problem, the above might still be necessary.

**Comment by arnaudframmery** [comment]
I will try to check that at the end of the week, thank for the report :)

**Comment by andreasharbo** [comment]
New observation: When i right click i have no issues. So it is definitely what is described above that is the problem.

**Comment by arnaudframmery** [comment]
I let you check the PR and give me a feedback, especially with PyQt 5.12

I added some logs when focus in or out of a widget and when a key is pressed to facilitate the work on this issue
